- name: Variables using file
  hosts: localhost
  vars_files:
    - variable.yaml
  tasks:
    - name: print variable files
      ansible.builtin.debug:
        msg: "WE are Learning {{ Name }} and the trainer is {{ TRAINER }} and the duration is {{ DURATION }}"