- name: Variable at task level
  hosts: localhost
  vars:
    money: "1 Lakh Rupees"
    land: "10 Acres"
  tasks:
    - name: inherit values from play
      ansible.builtin.debug:
        msg: "MONEY is {{ money }} and Land is {{ land }}"

    - name: inherit values from play and add values
      vars:
        money: "5 Lakh Rupees"
        land: "2 Acres"
        houses: "2 houses"
      ansible.builtin.debug:
        msg: "MONEY is {{ money }} and Land is {{ land }} and houses are {{ houses }}"