- name: ansible variable datatypes
  hosts: localhost
  vars:
    name: Madhu # string
    age: 25 # integer number
    isdevops: true # boolean
    skills: # list
      - devops
      - aws
      - Docker
    Experience: # map
      devops: 2
      aws: 1
      Docker: 5

  tasks: 
    - name: print variable number
      ansible.builtin.debug:
        msg: "{{ age }}"
    - name: print string variable
      ansible.builtin.debug:
        msg: "{{ name }}"
    - name: print boolean variable
      ansible.builtin.debug:
        msg: "{{ isdevops }}"
    - name: print list variables
      ansible.builtin.debug:
        msg: "{{ skills }}"
    - name: print map variables
      ansible.builtin.debug:
        msg: "{{ Experience }}"