- name: create user
  hosts: localhost
  tasks:
    - name: check roboshop user exit or not
      ansible.builtincommand: id roboshop
      register: result
    - name: print the command output
      ansible.builtin.debug:
        msg: "output is: {{ output }}"
  