- name: Install packages
  hosts: mongodb
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: nginx, state: present }
        - { name: postfix, state: present }
        - { name: maven, state: present }